spring.application.name=resilient-checkout-api
spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

resilience4j.circuitbreaker.instances.paymentService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.paymentService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.paymentService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.paymentService.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.paymentService.recordExceptions[0]=java.lang.Exception

resilience4j.retry.instances.paymentService.maxAttempts=3
resilience4j.retry.instances.paymentService.waitDuration=500ms

management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
